// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deleteChirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirps = `-- name: DeleteChirps :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChirps(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirps, id)
	return err
}
